---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: precise64
    driver_config:
      box: default
      box_url: http://files.vagrantup.com/precise64.box

suites:
  - name: default
    run_list:
      - recipe[skeleton-service-cookbook::default]
    attributes:
